package org.quantum.app;

import org.onlab.packet.Ip4Address;
import org.onosproject.net.ConnectPoint;
import org.onosproject.net.Device;
import org.onosproject.net.DeviceId;
import org.onosproject.net.OchSignal;
import org.onosproject.net.device.DeviceService;
import org.onosproject.net.intent.Intent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.onosproject.cli.AbstractShellCommand.get;

public class QkdApp {
    private final Logger log = LoggerFactory.getLogger(getClass());

    QkdAppManager manager = get(QkdAppManager.class);

    DeviceService deviceService = get(DeviceService.class);

    //These parameters are loaded from REST
    protected Ip4Address appAddress;
    protected int appPort;
    protected Ip4Address kmAddress;
    protected int kmPort;

    //These parameters are generated by the SDN controller
    protected String saeId;
    protected Device location;

    //These parameters are optional and loaded from REST
    protected Ip4Address partnerAppAddress;
    protected int partnerAppPort;
    protected String partnerAppQos;

    public QkdApp(Ip4Address appA, int appP, Ip4Address kmA, int kmP) {
        //Requires that id is a positive integer less < 10000, four digits
        String prefix = "12345678-abcd-abcd-abcd-00000000";

        appAddress = appA;
        appPort = appP;
        kmAddress = kmA;
        kmPort = kmP;

        DeviceId deviceId = DeviceId.deviceId("netconf:" + kmAddress.toString() + kmPort);
        location = deviceService.getDevice(deviceId);

        saeId = prefix + String.format("%04d", manager.getDatabaseSize() + 1);
        manager.addQkdApp(saeId, this);
    }
}
